[package]
name = "cs407_server"
version = "0.1.0"
authors = ["kyrime <kyrime@no.email>"]

[lib]
crate-type = ["dylib"]

[dependencies]
time = "0.1.38"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.6", default-features = false }
